# parameters file for docker image 

# 1. sudo docker pull microstrain/ros-microstrain_inertial_driver:ros

# 2. In RosDockerWorkspace, run: 

# $ sudo docker run -it --rm --net=host --device=/dev/ttyACM1 -v "/home/hopper/Documents/git_workspace/RosDockerWorkspace/src/RExHopper/params.yml:/tmp/params.yml" microstrain/ros-microstrain_inertial_driver:ros params_file:=/tmp/params.yml port:=/dev/ttyACM1

# 3. You can check what it's publishing with
# $ rostopic list

filter_declination_source: 1